quals_data = "https://docs.google.com/spreadsheets/d/1q6pLvgrr1z5WB1FYFp2rCeO86mvTMy2L10Uu59aWul8/edit#gid=774124636"
country_data = "https://docs.google.com/spreadsheets/d/1q6pLvgrr1z5WB1FYFp2rCeO86mvTMy2L10Uu59aWul8/edit#gid=1806021551"
beatmap_metadata = "https://docs.google.com/spreadsheets/d/1q6pLvgrr1z5WB1FYFp2rCeO86mvTMy2L10Uu59aWul8/edit#gid=2099614788"
player_usernames = "https://docs.google.com/spreadsheets/d/1q6pLvgrr1z5WB1FYFp2rCeO86mvTMy2L10Uu59aWul8/edit#gid=716522660"
